### ISSUE TITLE
When do you plan on turn on Teams

### ISSUE THREAD

**Issue by jcrupi** [p2-inc/keycloak-orgs#152]
We could really use it. We don't want to use KeyCloak groups.

**Comment by xgp** [comment]
Teams is not on the roadmap. It was initially imported ~3 years ago, because this library was based on some work for a customer, but there was never any demand for it. There have been a couple of relevant discussions:
- https://github.com/p2-inc/keycloak-orgs/issues/86
- https://github.com/p2-inc/keycloak-orgs/issues/148
But nothing has been implemented yet.

**Comment by jcrupi** [comment]
So any best practices you recommend to have a group or team of members associated with a organization?

**Comment by xgp** [comment]
Not at this time.
