### ISSUE TITLE
Question: Fetching organizations for currently authenticated user doesnot reveal domains like fetching all organizations. For purpose?

### ISSUE THREAD

**Issue by jaakkom** [p2-inc/keycloak-orgs#182]
Hello,
Noticed that fetching organizations for currently authenticated user has different payload what fetching all organizations gives:

![image](https://github.com/p2-inc/keycloak-orgs/assets/1277004/9f9c779b-66e9-4f53-a32b-edc05adb8f59)
 VS
 
![image](https://github.com/p2-inc/keycloak-orgs/assets/1277004/e0412f31-9dfb-45e9-9665-1e1f4a0bba91)

Is there some reason behind this? I think it would be useful to have all same fields in both apis.

**Comment by xgp** [comment]
The “me” endpoint was originally meant to be a brief representation of the logged in users’ orgs, rather than a full representation. 

If it is possible to extend the object without breaking backwards compatibility, we’d look at a PR that takes a “briefRepresentation=false” flag in that method and returns more data.
