### ISSUE TITLE
Organization user with 'manage-organization' role cannot delete the organization

### ISSUE THREAD

**Issue by youssefbennour** [p2-inc/keycloak-orgs#263]
I'm integrating your API in my .NET application.
Actually, when the user creates an organization, he's assigned all roles in the organization including 'manage-organization'.
When I try to delete the organiztion by the user, I get an Unauthroized status code.
This only works when the user is gobally assigned the realm-management role 'manage-organizations', which gives him access to manage all realm Organizations => can delete all realm organizations, but I only want him to be able to perform this action in organiztions he's part of.
Is this the behavior by design ? or is it a bug ?

**Comment by xgp** [comment]
That is by design. The original design was to allow only users with the `realm-management` role `manage-organizations` to be able to create and delete organizations. An additional `create-organization` role was added to allow create without the other permissions, but no other role exists to delete organizations.

**Comment by justvdv** [comment]
@xgp We're also facing the issue where only users with the realm-management role manage-organizations can delete organizations, even though the documentation under [Docs → Organizations → Roles](https://phasetwo.io/docs/organizations/roles/) indicates that the default manage-organization role should allow both updating and deleting an organization.

Given that we're dealing with low contract value per user, being able to delete an organization at the organization level is crucial for maintaining our service in the long run. We understand that this might be a design decision, but would you be open to considering a change so that the behavior aligns with the documentation? We would be happy to contribute to implementing this change if that would help.

Thank you for your consideration.

**Comment by xgp** [comment]
I’d accept a PR for a new default organization role (e.g. “delete-organization”) that can do it.
