### ISSUE TITLE
adding count organizations endpoint

### ISSUE THREAD

**Issue by paulwer** [p2-inc/keycloak-orgs#73]
Hey everyone,
we're integrating p2-orgs within our system and wanted to have a standard way to get the whole count of available orgs. are we missing something or is this a possible pr?

**Comment by xgp** [comment]
Hi @paulwer thanks for the suggestion. There is no method to get the count of orgs. Right now, you'd have to use this https://phasetwo.io/api/get-organizations and paginate through them all in order to count them. I think a count method would be a great addition, in a similar format to how keycloak does groups counts. E.g. something like `/realms/{realm}/orgs/count` that takes an optional `search` query string. PR most welcome for this.

**Comment by xgp** [comment]
added `/realms/{realm}/orgs/count` endpoint in #79

**Comment by paulwer** [comment]
@xgp is there a need to add this also to keycloak-js js library?

**Comment by xgp** [comment]
@paulwer I'm assuming you mean the sdk client libs. Yes, the sdk libs need to get updated with the changes.
