### ISSUE TITLE
[Question] New license

### ISSUE THREAD

**Issue by henriqueof** [p2-inc/keycloak-orgs#81]
So, after commit [4f52192](https://github.com/p2-inc/keycloak-orgs/commit/4f52192508d04637c7ff8e6484e63bb88726ebdb) it is not possible to use this plug-in in any kind of hosted product.
Despite initially considering dropping this incredible piece of code in my current SaaS side project, I decided to reach out and ask if you are considering any kind "special" license for people who want to use it in hosted solutions like me.

**Comment by xgp** [comment]
@henriqueof Thanks for the question. I think there is some confusion about how the license applies. If you are a SaaS company that is providing a product that does not offer the features of this product itself AS A SERVICE, then you can absolutely use this in your project. 

For example, if you are selling shared storage as a service (like Dropbox), and you use Keycloak and this extension to manage your users and allow them to form "teams" in their organizations, then that is a permitted use case under the license. 

Alternately, there are many companies that offer Keycloak-as-a-Service (e.g. Cloud-IAM and Elestio). If they were to bundle this extension in their offering that would be a violation of the license.

A good set of questions to ask is:
- Am I offering Keycloak, user management or other identity and access management features AS A SERVICE TO MY CUSTOMERS?
- Am I substantially competitive with the offering of [Phase Two's](https://phasetwo.io/) or other Keycloak-as-a-Service companies?

If the answer to those is "yes", then you can't use it without a special license.

There are **many** SaaS companies that are using Keycloak with this extension to provide services that have nothing to do with IAM, and the Elastic v2 license permits this. The goal of using this license is to prevent a competitor from popping up, taking the extensions, and providing Keycloak-as-a-Service in a way that is competitive with us. Elastic (the company behind the license), did this because of AWS's move to host their offering.

More information is on the [blog post we wrote about the license change](https://phasetwo.io/blog/licensing-change), but feel free to help us with language if the descriptions are confusing.
