### ISSUE TITLE
FR: extend default roles by api

### ISSUE THREAD

**Issue by paulwer** [p2-inc/keycloak-orgs#82]
Is there currently a way to extend the default roles of organizations by custom roles, which then are applied by default for all organizations?

Usage: we had ressources, which are connected to organizations and want to manage access within the organizations without writing a programm which checks any org, if the neccessary roles are defined. ex. view-ressources-name, manage-ressources-name

**Comment by xgp** [comment]
Without an example, I'm not sure what you're suggesting. Today, an OrganizationRole is associated with an Organization. There are defaults when you create an Organization that pertain to permissions within the role (e.g. `view-organiztion`, `manage-organization`, etc.), and OrganizationRoles are not shared across Organizations.

We put together a proposal for de-coupling that, so that OrganizationRoles are independent of Organizations:  https://github.com/p2-inc/keycloak-orgs/issues/48 Is that what you're looking for? If not, share an example scenario.

**Comment by paulwer** [comment]
![Unbenannt](https://github.com/p2-inc/keycloak-orgs/assets/52678724/b34407c9-0cea-49d5-9922-f99688f5792c)

Organizations has definded and default roles. default roles (my observation) gets created on organization-creation and cannot be deleted. They are used for rbac within org-use-cases. defined-roles can be created within each org-individualy. 
Our "wish" is, that we can administrate additional default-roles, which can be used within all organizations independently.

Our current workflow-plan is to create a service, which checks and define these additional roles, as needed.

**Comment by xgp** [comment]
Closing in favor of https://github.com/p2-inc/keycloak-orgs/issues/48 

Please comment there.
